### PR TITLE
Add info about how to ask for reviews

### PR DESCRIPTION
**Pull request by rt4914**
## Context
I recently created my first PR on forem https://github.com/forem/forem/pull/14343 and in that after finishing the template I assigned it to team-members so that they can review it. I did this because on my previous project we used the **Assignees** section to point to the person who needs to take action.

After discussion with @citizen428 I got to know that I should have tagged reviewers and should not have used the **Assignees** section.

Therefore I created this PR so that any new contributor already knows how to request for a PR review.

### CODE REVIEW

**Comment by rt4914** [comment]
@citizen428 @joshpuetz PTAL (Please take a look) and feel free to suggest changes.

**Review by joshpuetz — APPROVED** [review]

**Review by citizen428 — APPROVED** [review]

**Comment by rt4914** [comment]
@joshpuetz and @citizen428 considering there are two approvals should I merge this PR or someone else will do that?

**Comment by joshpuetz** [comment]
> @joshpuetz and @citizen428 considering there are two approvals should I merge this PR or someone else will do that?

You should go ahead and merge it @rt4914: we always have the PR creator make the decision to merge!

**Comment by rt4914** [comment]
> > @joshpuetz and @citizen428 considering there are two approvals should I merge this PR or someone else will do that?
> 
> You should go ahead and merge it @rt4914: we always have the PR creator make the decision to merge!

Thanks @joshpuetz

**Pull request merged**
