### PR TITLE
Add missing user_id fields to API definition

### PR DESCRIPTION
**Pull request by fdocr**
Ensures the API docs reflect the changes made by https://github.com/forem/forem/pull/18214

### CODE REVIEW

**Review by joshpuetz — DISMISSED** [review]
Approving only because these are being added to the V0 api!

**Review by joshpuetz — CHANGES_REQUESTED** [review]
In order to be valid, the definition for the user_id field needs to be added to both `SharedUser` around line 940, and `Follower` around line 706 like this (these are the objects you added the example return user_id to, but without that field defined in the schema it will be invalid)

`    user_id:
          type: integer
          format: int32
`

**Comment by fdocr** [comment]
I just updated with the changes requested above. Also, there's a more in-depth review of the results from the change [in this comment](https://github.com/forem/forem/pull/18214#issuecomment-1199700975).

But in summary, by updating the `SharedUser` and `Follower` schemas the new field trickles down to endpoints that reference them. For example `/api/readingist`:

Screen Shot 2022-07-29 at 10 30 17

**Review by joshpuetz — APPROVED** [review]

**Comment by fdocr** [comment]
@joshpuetz would you mind merging this PR? It seems like I can't merge it myself. It seems like `main` is a protected branch, maybe something changed in that config? 🤔 

Screen Shot 2022-08-03 at 10 51 59

**Comment by joshpuetz** [comment]
Done, and will fix permission @fdocr!

**Pull request merged**
